{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rakuten.android",
    "module": "rewardsdknative-bom",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-client",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-core",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-event",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-ext",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-remote",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-sps",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-ui",
          "version": {
            "requires": "7.1.1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-client",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-common",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-core",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-event",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-ext",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-remote",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-sps",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.rakuten.android",
          "module": "rewardsdknative-ui",
          "version": {
            "requires": "7.1.1"
          }
        }
      ]
    }
  ]
}
